server:
  port: 8080
  servlet:
    context-path: /docker

spring:
  application:
    name: dockerDemo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

scheduler:
  interval: "*/10 * * * * *"